<?php
// Initialize routing and load config
require_once __DIR__ . '/../app/config/constants.php';
require_once __DIR__ . '/../app/config/session.php';
require_once __DIR__ . '/../app/config/database.php';

// Security Headers
header("X-Frame-Options: SAMEORIGIN");
header("X-Content-Type-Options: nosniff");
header("X-XSS-Protection: 1; mode=block");
header("Referrer-Policy: strict-origin-when-cross-origin");
header("Content-Security-Policy: default-src 'self' cdn.jsdelivr.net fonts.googleapis.com fonts.gstatic.com; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net fonts.googleapis.com; script-src 'self' 'unsafe-inline' cdn.jsdelivr.net;");

// Simple Front Controller Router
$url = isset($_GET['url']) ? rtrim($_GET['url'], '/') : 'home';
$url = filter_var($url, FILTER_SANITIZE_URL);
$urlParts = explode('/', $url);

$controller = strtolower($urlParts[0]);
$action = isset($urlParts[1]) ? strtolower($urlParts[1]) : 'index';

// Start session securely for all routes except maybe API/webhook later
start_session_securely();

// Extremely basic routing logic
switch ($controller) {
    case 'home':
        require_once __DIR__ . '/../app/views/auth/landing.php';
        break;

    case 'login':
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            require_once __DIR__ . '/../app/controllers/AuthController.php';
            $auth = new AuthController();
            $auth->login();
        } else {
            // Retrieve any flash error messages generated by AuthController
            $error = $_SESSION['error'] ?? '';
            unset($_SESSION['error']);
            require_once __DIR__ . '/../app/views/auth/login.php';
        }
        break;

    case 'student-login':
        require_once __DIR__ . '/../app/controllers/StudentController.php';
        $studentCtrl = new StudentController();
        $studentCtrl->login();
        break;

    case 'admin':
        require_once __DIR__ . '/../app/controllers/AdminController.php';
        $adminCtrl = new AdminController();
        if ($action === 'students') {
            $adminCtrl->students();
        } else if ($action === 'edit-student') {
            $adminCtrl->editStudent();
        } else if ($action === 'delete-student') {
            $adminCtrl->deleteStudent();
        } else if ($action === 'add-student') {
            $adminCtrl->addStudent();
        } else if ($action === 'teachers') {
            $adminCtrl->teachers();
        } else if ($action === 'add-teacher') {
            $adminCtrl->addTeacher();
        } else if ($action === 'edit-teacher') {
            $adminCtrl->editTeacher();
        } else if ($action === 'delete-teacher') {
            $adminCtrl->deleteTeacher();
        } else if ($action === 'subjects') {
            $adminCtrl->subjects();
        } else if ($action === 'add-subject') {
            $adminCtrl->addSubject();
        } else if ($action === 'edit-subject') {
            $adminCtrl->editSubject();
        } else if ($action === 'delete-subject') {
            $adminCtrl->deleteSubject();
        } else if ($action === 'subject-students') {
            $adminCtrl->subjectStudents();
        } else if ($action === 'unenroll-student') {
            $adminCtrl->unenrollStudent();
        } else if ($action === 'assign-teacher') {
            $adminCtrl->assignTeacher();
        } else if ($action === 'assign-student') {
            $adminCtrl->assignStudent();
        } else if ($action === 'reports') {
            $adminCtrl->reports();
        } else {
            $adminCtrl->dashboard();
        }
        break;

    case 'teacher':
        require_once __DIR__ . '/../app/controllers/TeacherController.php';
        $teacherCtrl = new TeacherController();
        if ($action === 'mark') {
            $teacherCtrl->markAttendance();
        } else if ($action === 'view-report') {
            $teacherCtrl->viewReport();
        } else if ($action === 'export-csv') {
            $teacherCtrl->exportCsv();
        } else {
            $teacherCtrl->dashboard();
        }
        break;

    case 'student':
        require_once __DIR__ . '/../app/controllers/StudentController.php';
        $studentCtrl = new StudentController();
        $studentCtrl->dashboard();
        break;

    case 'logout':
        session_destroy();
        session_unset();
        setcookie(session_name(), '', time() - 3600, '/');
        header("Location: " . APP_URL);
        exit;

    case 'api':
        if(isset($urlParts[1]) && strtolower($urlParts[1]) === 'mark') {
            require_once __DIR__ . '/../app/controllers/AttendanceController.php';
            $apiController = new AttendanceController();
            $apiController->apiMark();
        } else {
            http_response_code(404);
            header("Content-Type: application/json");
            echo json_encode(['status'=>'error', 'message'=>'API endpoint not found']);
        }
        break;

    default:
        http_response_code(404);
        echo "<h1>404 Not Found</h1>";
        break;
}
